### ISSUE TITLE
Crashes with negative timestamp

### ISSUE THREAD

**Issue by yardinicwaller** [abutaha/aws-es-proxy#11]
aws-es-proxy is *almost* working great for me. I can get it started up and make a few requests, but it consistently crashes after about a minute.

```
$ ./aws-es-proxy-0.3-mac-amd64 -endpoint https://REDACTED.ca-central-1.es.amazonaws.com -verbose
Listening on 127.0.0.1:9200
2017/09/20 21:22:55  -> GET / 200 0.460s
2017/09/20 21:22:55  -> GET /_cluster/health 200 0.461s
2017/09/20 21:22:55  -> GET /_cluster/health 200 0.460s
2017/09/20 21:22:55  -> GET / 200 0.462s
2017/09/20 21:22:55  -> GET /_cat/nodes?format=json 200 0.465s
[... 110 lines skipped ...]
2017/09/20 21:23:54  -> GET /_aliases 200 0.379s
2017/09/20 21:23:54  -> GET /_nodes/_all/os,jvm?human=true 200 0.379s
2017/09/20 21:23:54  -> GET /_nodes/stats/jvm,fs,os,process?human=true 200 0.385s
1969/12/31 16:00:00  -> GET /_stats/docs,store 200 -1505967819.950s
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x166280]
```

Notice that the last request has a timestamp at the beginning of the epoch, and the request duration is similarly computed as a difference between current time and epoch.

Here's the stack trace:

```
goroutine 34 [running]:
runtime.throw(0x5841e0, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc820571718 sp=0xc820571700
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc820571768 sp=0xc820571718
sync.(*Pool).Get(0x73b310, 0x0, 0x0)
	/usr/local/go/src/sync/pool.go:102 +0x40 fp=0xc8205717b8 sp=0xc820571768
fmt.newPrinter(0x1)
	/usr/local/go/src/fmt/print.go:133 +0x27 fp=0xc8205717f8 sp=0xc8205717b8
fmt.Sprintf(0x5363b0, 0x13, 0xc820571ab0, 0x4, 0x4, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:202 +0x2b fp=0xc820571848 sp=0xc8205717f8
log.Printf(0x5363b0, 0x13, 0xc820571ab0, 0x4, 0x4)
	/usr/local/go/src/log/log.go:289 +0x49 fp=0xc820571898 sp=0xc820571848
main.(*proxy).ServeHTTP(0xc820092910, 0x8becc8, 0xc82025a000, 0xc8202f8b60)
	/Users/abutaham/go-libs/src/github.com/abutaha/aws-es-proxy/aws-es-proxy.go:138 +0xc3b fp=0xc820571b70 sp=0xc820571898
net/http.serverHandler.ServeHTTP(0xc820094380, 0x8becc8, 0xc82025a000, 0xc8202f8b60)
	/usr/local/go/src/net/http/server.go:2081 +0x19e fp=0xc820571bd0 sp=0xc820571b70
net/http.(*conn).serve(0xc820172000)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e fp=0xc820571f98 sp=0xc820571bd0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820571fa0 sp=0xc820571f98
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e

goroutine 1 [IO wait]:
net.runtime_pollWait(0x8bea78, 0x72, 0x8b9028)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820124370, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820124370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820124310, 0x0, 0x8beb70, 0xc8200d9dc0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82008e078, 0x54780, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82008e078, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(*Server).Serve(0xc820094380, 0x8beb38, 0xc82008e078, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(*Server).ListenAndServe(0xc820094380, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0x4f7ac0, 0xe, 0x8bda78, 0xc820092910, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2195 +0x98
main.main()
	/Users/abutaham/go-libs/src/github.com/abutaha/aws-es-proxy/aws-es-proxy.go:170 +0x63e
```

**Steps to reproduce**

I'm only doing one thing that might be unusual -- I'm trying to run the [cerebro](https://github.com/lmenezes/cerebro) Elasticsearch web management GUI through aws-es-proxy. 

1. Start aws-es-proxy in verbose mode against AWS ES endpoint in ca-central-1 using ~/.aws/credentials
2. Start cerebro on port 9000
3. Log into cerebro web UI and connect to http://127.0.0.1:9000/
4. Wait about one minute for aws-es-proxy to crash

**Other details**

- aws-es-proxy version 0.3
- Operating system: macOS 10.12.6

**Comment by yardinicwaller** [comment]
Looks like version 0.4 is fine. I'm no longer able to reproduce the issue on 0.4.
